import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "./components/common/Header.js";
import Footer from "./components/common/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body className={`${inter.variable}`}>{children}</body>
      <Footer />
    </html>
  );
}
